### PR TITLE
Switched "all" methods return from sessionData[] to { [sid: string]: sessionData }

### PR DESCRIPTION
**Pull request by master117**
**What:**
Switched "all" methods return from `sessionData[]` to `{ [sid: string]: sessionData }`,
so it is possible to retrieve the sid of all sessions. Adjusted documentation.

**Why:**
I wanted to use the all method to find all sessions and then destroy all sessions for certain users / tokens. Without the sid it's not possible to destroy certain sessions. And my first implementation for the all method would not include sids.

**Why not: { sid: string, data: sessionData }[]**
I actually would have prefered to return` { sid: string, data: sessionData }[]` to easily link sid and session data but when looking at express-session index.d.ts I only found:

`all: (callback: (err: any, obj?: { [sid: string]: Express.SessionData; } | null) => void) => void;`

### CODE REVIEW

**Comment by master117** [comment]
I tried adjusting tests, but I'm not sure what is the best way to test this, since sids are randomized.

**Comment by JLuboff** [comment]
I'll give this a review tomorrow. Thank you!

**Review by JLuboff — CHANGES_REQUESTED** [review]
Ok, just a few items.

1. Can you parse the results into your return object? `returnObject[result.recordset[i].sid] = JSON.parse(result.recordset[i].session)`
2. In `store.test.ts`, please update the `store.all` test (line 96) to expect the following
```
expect(Object.keys(session)).toHaveLength(2);
        expect(session['5678DEF'].somevalue).toBe('yes');
```
After that, we'll be good to merge!

**Comment by master117** [comment]
>Can you parse the results into your return object
Of course, my bad.

Tests adjusted as well.

**Review by JLuboff — APPROVED** [review]

**Comment by JLuboff** [comment]
Merged! I'll get it onto NPM shortly

**Pull request merged**
